# Data Cleaning Project - Retail Store Sales

This project focuses on cleaning and preparing a raw dataset using Python and important Liabraries.
The dataset contains several common data quality issues such as missing values,
duplicate records, incorrect data types, inconsistent values and many more.

The goal of this project is to transform the raw dataset into a clean and reliable dataset
that can be used for Analysis and EDA.

## Importing Required Libraries

In this step, we import the necessary Python libraries that will be used for
data manipulation and analysis.

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.simplefilter(action='ignore', category='futurewarning')

## Loading the Dataset

The dataset is loaded into a Pandas DataFrame to begin the data cleaning process.

In [2]:
df = pd.read_csv(r'c:\Users\AYUSH\Downloads\retail_store_sales.csv')

## Dataset Overview

Here is the overview on first and last 5 rows of the dataset

In [3]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [4]:
df.tail()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN

## Understanding the Dataset

Before cleaning the data, it is important to explore the dataset to understand
its structure, columns and potential issues.

In [5]:
print('\nNumber of rows:', df.shape[0])
print('\nNumber of Columns:', df.shape[1])
print('\nInformation about the Data:\n')
df.info()
print('\nDescription of the data')
df.describe()

Number of rows: 12575

Number of Columns: 11

Information about the Data:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

Description of the data

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [6]:
# As we can see in the information that the datatypes are incorrect for some columns that needs to be changed.
# also need to handle outliers which we can see in the description

## Checking Missing Values

Missing values can affect the accuracy of analysis. In this step, we identify
missing values and decide how to handle them.

In [7]:
df.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [8]:
# Few columns contaion null values that we will fill with the help of 
# mean, median or mode whichever suits perfect and also need to drop specific columns.

## Identifying Removing Duplicate Records

Duplicate rows can distort the dataset and affect analysis results.
In this step, duplicate records are identified and removed.

In [9]:
print('Number of Duplicates:', df.duplicated().sum())

Number of Duplicates: 0

In [10]:
# There are no duplicates in the dataset so we don't need to remove any.

## Droping Columns

Few columns need to be droped that are not much necessary for the data

In [11]:
df.drop(['Item', 'Discount Applied'], axis=1, inplace=True)


The **Item** column was removed because it mostly contained the same information as the **Category** column along with some extra numbers and text, making it redundant for the analysis.

The **Discount** column was also removed because it only contained True/False values and did not appear to be meaningfully applied in the dataset.

# Filling Missing Data

In [12]:
df.isna().sum()

Transaction ID        0
Customer ID           0
Category              0
Price Per Unit      609
Quantity            604
Total Spent         604
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [13]:
df.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [14]:
# Before we fill the missing data we need to make sure that the Total Spent column is correct.
 
df['Total Spent'] = df['Price Per Unit'] * df['Quantity']

In [15]:
miss = ['Price Per Unit', 'Quantity', 'Total Spent']
df[miss] = df[miss].fillna(df[miss].median())

In [16]:
df.isna().sum()

Transaction ID      0
Customer ID         0
Category            0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [17]:
# The columns Price Per Unit, Quantity, and Total Spent contain missing values.  
# To handle this issue, the median of each column is used to fill the missing values
# because it is less affected by outliers and better represents the typical value.

## Correcting Data Types

Some columns may have incorrect data types so we need to convert them into appropriate format.

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Price Per Unit    12575 non-null  float64
 4   Quantity          12575 non-null  float64
 5   Total Spent       12575 non-null  float64
 6   Payment Method    12575 non-null  object
 7   Location          12575 non-null  object
 8   Transaction Date  12575 non-null  object
dtypes: float64(3), object(6)
memory usage: 884.3+ KB

In [19]:
# For Category Type:
cat = ['Location','Category','Payment Method']
df[cat] = df[cat].astype('category')

# For int Type:
df['Quantity'] = df['Quantity'].astype('int')

# For Date Type:
df['Transaction Date'] =  pd.to_datetime(df['Transaction Date'], errors='coerce')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  category
 3   Price Per Unit    12575 non-null  float64
 4   Quantity          12575 non-null  int64
 5   Total Spent       12575 non-null  float64
 6   Payment Method    12575 non-null  category
 7   Location          12575 non-null  category
 8   Transaction Date  12575 non-null  datetime64[ns]
dtypes: category(3), datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 627.0+ KB

## Final Clean Dataset

In [21]:
df.head(10)

,Transaction ID,Customer ID,Category,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date
0,TXN_6867343,CUST_09,Patisserie,18.5,10,185.0,Digital Wallet,Online,2024-04-08
1,TXN_3731986,CUST_22,Milk Products,29.0,9,261.0,Digital Wallet,Online,2023-07-23
2,TXN_9303719,CUST_02,Butchers,21.5,2,43.0,Credit Card,Online,2022-10-05
3,TXN_9458126,CUST_06,Beverages,27.5,9,247.5,Credit Card,Online,2022-05-07
4,TXN_4575373,CUST_05,Food,12.5,7,87.5,Digital Wallet,Online,2022-10-02
5,TXN_7482416,CUST_09,Patisserie,23.0,10,108.5,Credit Card,Online,2023-11-30
6,TXN_3652209,CUST_07,Food,5.0,8,40.0,Credit Card,In-store,2023-06-10
7,TXN_1372952,CUST_21,Furniture,33.5,6,108.5,Digital Wallet,In-store,2024-04-02
8,TXN_9728486,CUST_23,Furniture,27.5,1,27.5,Credit Card,In-store,2023-04-26
9,TXN_2722661,CUST_25,Butchers,36.5,3,109.5,Cash,Online,2024-03-14

In [22]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Category            0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [23]:
print('Number of duplicates:',df.duplicated().sum())

Number of duplicates: 0



After applying all cleaning steps, the dataset is now consistent and ready
for further analysis or visualization.

## Conclusion

In this project, the dataset was cleaned by:

- Handling missing values
- Droping unnecessary columns
- Correcting data types
- Fixing invalid values

The cleaned dataset is now ready for data analysis and visualization.

In [24]:
# df.to_csv("cleaned_again_Retail_store.csv", index=False)